# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shoppingListV2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shoppingListV2
pod ‘Firebase’
pod ‘Database’
pod ‘Kingfisher’
pod ‘Firebase/Core’
pod ‘Firebase/Database’


  target 'shoppingListV2Tests' do
    inherit! :search_paths
    # Pods for testing


 end

end
